# Use an official Python runtime as a parent image
FROM python:3.7.2-alpine3.9 AS pylogin

# Set the working directory to /app
WORKDIR /myflixKafka

# Copy the current directory contents into the container at /app
COPY . /myflixKafka

# Install any needed packages specified in requirements.txt
RUN \
 pip install --trusted-host pypi.python.org -r requirements.txt --no-cache-dir

# Make port 80 available to the world outside this container
EXPOSE 8080

# Define environment variable
# ENV NAME World

# Run video.py when the container launches
# CMD ["python3", "postgres_login.py"]
